export const homeCopy = {
  en: {
    eyebrow: "A focused terminal coding agent",
    title: ["Your terminal.", "Your coding partner."],
    description: "From the first question to the passing test. Work with an agent that reads your project, explains its steps, and keeps you in control.",
    start: "Get started",
    guide: "Explore the guide",
    install: "Install with uv",
    copied: "Copied",
    copyFailed: "Select and copy the command",
    requirements: "Python 3.10+ · macOS, Linux & Windows · OpenAI-compatible APIs",
    previewTitle: "Real tools. A readable conversation.",
    previewDescription: "Follow the reasoning, review the commands, and keep working without leaving your terminal.",
    previewAlt: "ZettCode terminal: a pixel robot welcomes you, a task is followed by thinking, file reads, a code edit, a test run, and a Markdown answer.",
    previewCaption: "Illustrative conversation, rendered with ZettCode’s actual terminal widgets. No API request required.",
    principles: [
      { number: "01", title: "See what happens.", text: "Thoughts, answers, and tool calls arrive in order. Read the work as a conversation, not a wall of JSON.", link: "/guide/interface", label: "Explore the interface" },
      { number: "02", title: "Stay in the loop.", text: "Review shell commands before they run. Answer questions, steer a reply, or ask a side question with /btw.", link: "/guide/commands", label: "Find your commands" },
      { number: "03", title: "Pick up where you left off.", text: "Resume a session, manage its context, and export a readable HTML record. Your project has a history.", link: "/guide/sessions", label: "Work with sessions" },
    ],
    pathEyebrow: "A guide that meets you where you are",
    pathTitle: "Less searching. More making.",
    paths: [
      { title: "Start here", text: "Install, connect a model, and send your first task.", links: [{ label: "Getting started", path: "getting-started" }, { label: "The interface", path: "interface" }] },
      { title: "Make it a daily tool", text: "Learn the shortcuts and keep conversations moving.", links: [{ label: "Keys & mouse", path: "keys" }, { label: "Commands", path: "commands" }, { label: "Sessions", path: "sessions" }] },
      { title: "Make it yours", text: "Choose models, teach it your project, and connect tools.", links: [{ label: "Configuration", path: "config" }, { label: "Models & context", path: "models" }, { label: "Project instructions", path: "instructions" }, { label: "Skills & MCP", path: "skills-and-mcp" }, { label: "Plugins", path: "plugins" }] },
    ],
    help: "Need a hand?",
    faq: "Problems & questions",
    source: "Read the source on GitHub",
  },
  zh: {
    eyebrow: "专注的终端编码智能体",
    title: ["你的终端。", "你的编码伙伴。"],
    description: "从第一个问题，到测试通过。读懂项目、展示过程，把决定权留给你，让想法在熟悉的终端里变成代码。",
    start: "快速开始",
    guide: "浏览使用指南",
    install: "使用 uv 安装",
    copied: "已复制",
    copyFailed: "请选中并复制这条命令",
    requirements: "Python 3.10+ · macOS、Linux 与 Windows · OpenAI 兼容接口",
    previewTitle: "真实的工具，清楚的对话。",
    previewDescription: "跟上思路、审阅命令、继续工作，不必离开终端。",
    previewAlt: "ZettCode 终端：像素机器人欢迎你，任务之后依次展示思考、读文件、改代码、运行测试，以及 Markdown 回答。",
    previewCaption: "示例对话由 ZettCode 的实际终端组件渲染，无需调用模型接口。",
    principles: [
      { number: "01", title: "看清每一步。", text: "思考、回答与工具调用按顺序呈现。读到的是一段对话，而不是一墙 JSON。", link: "/zh/guide/interface", label: "认识界面" },
      { number: "02", title: "决定权在你手上。", text: "运行 shell 命令前先审阅。回答问题、追加引导消息，或用 /btw 问一句不进入后续上下文的旁路问题。", link: "/zh/guide/commands", label: "查看命令" },
      { number: "03", title: "随时接着做。", text: "恢复会话、管理上下文，导出便于阅读的 HTML。项目里的工作有迹可循。", link: "/zh/guide/sessions", label: "使用会话" },
    ],
    pathEyebrow: "按你的使用阶段，找到下一步",
    pathTitle: "少一点查找，多一点创造。",
    paths: [
      { title: "第一次使用", text: "安装、连接模型，发出第一个任务。", links: [{ label: "快速开始", path: "getting-started" }, { label: "认识界面", path: "interface" }] },
      { title: "日常使用", text: "掌握快捷键，让对话与工作顺畅衔接。", links: [{ label: "快捷键与鼠标", path: "keys" }, { label: "命令参考", path: "commands" }, { label: "会话管理", path: "sessions" }] },
      { title: "按你的方式配置", text: "选择模型、说明项目约定、连接工具。", links: [{ label: "配置参考", path: "config" }, { label: "模型与上下文", path: "models" }, { label: "项目指令", path: "instructions" }, { label: "Skills 与 MCP", path: "skills-and-mcp" }, { label: "插件", path: "plugins" }] },
    ],
    help: "遇到问题？",
    faq: "常见问题",
    source: "在 GitHub 上查看源码",
  },
};
