"""ZettCode's internally implemented terminal UI framework."""

from __future__ import annotations

import importlib

#: Where each public name lives; read by :func:`__getattr__` on first use.
_EXPORTS = {
    "ARROW_DOWN": ".glyphs",
    "ARROW_UP": ".glyphs",
    "Anchor": ".layout",
    "AnyEvent": ".core",
    "AsyncInput": ".input",
    "BAR_EMPTY": ".glyphs",
    "BAR_FULL": ".glyphs",
    "Binding": ".core",
    "Border": ".layout",
    "Canvas": ".render",
    "Collapsible": ".widgets",
    "ColorDepth": ".render",
    "Column": ".widgets",
    "Command": ".core",
    "CommandRegistry": ".core",
    "Completer": ".widgets",
    "CompletionItem": ".widgets",
    "CompletionPopup": ".widgets",
    "Constraints": ".core",
    "DARK": ".core",
    "DONE": ".glyphs",
    "Dialog": ".widgets",
    "DialogAction": ".widgets",
    "DiffLine": ".widgets",
    "DiffSegment": ".widgets",
    "DiffView": ".widgets",
    "DifferentialRenderer": ".render",
    "ELLIPSIS": ".glyphs",
    "EXAMPLE": ".theme_file",
    "EXPANDED": ".glyphs",
    "EdgeInsets": ".core",
    "Event": ".core",
    "EventKind": ".core",
    "EventType": ".input",
    "FAILED": ".glyphs",
    "FocusEvent": ".core",
    "FocusManager": ".core",
    "HBox": ".layout",
    "HEADER": ".glyphs",
    "Host": ".core",
    "InputDecoder": ".input",
    "InputEvent": ".input",
    "KeyEvent": ".core",
    "Keymap": ".core",
    "LIGHT": ".core",
    "LineSource": ".layout",
    "ListItem": ".widgets",
    "ListPage": ".widgets",
    "ListView": ".widgets",
    "MARKER": ".glyphs",
    "Markdown": ".widgets",
    "MarkdownSource": ".widgets",
    "MarkdownView": ".widgets",
    "MouseAction": ".core",
    "MouseEvent": ".core",
    "Overlay": ".layout",
    "OverlaySlot": ".layout",
    "PENDING": ".glyphs",
    "PROMPT": ".glyphs",
    "Padding": ".layout",
    "PasteEvent": ".core",
    "Point": ".core",
    "ProgressBar": ".widgets",
    "RULE": ".glyphs",
    "RUNNING": ".glyphs",
    "Rect": ".core",
    "ResizeEvent": ".core",
    "RichText": ".widgets",
    "Rule": ".widgets",
    "SEPARATOR": ".glyphs",
    "SKIPPED": ".glyphs",
    "SPINNER": ".glyphs",
    "STATUS": ".glyphs",
    "Scheduler": ".core",
    "Screen": ".core",
    "ScreenStack": ".core",
    "ScrollView": ".layout",
    "Size": ".core",
    "Slot": ".layout",
    "Span": ".render",
    "Spinner": ".widgets",
    "StaticLines": ".layout",
    "StatusBar": ".widgets",
    "Style": ".render",
    "Table": ".widgets",
    "TaskPanel": ".widgets",
    "Terminal": ".terminal",
    "TerminalCapabilities": ".capabilities",
    "TerminalRunner": ".runner",
    "Text": ".widgets",
    "TextArea": ".widgets",
    "TextEvent": ".core",
    "TextLine": ".render",
    "Theme": ".core",
    "ThemeFileError": ".theme_file",
    "Toast": ".widgets",
    "ToolTheme": ".core",
    "Track": ".layout",
    "TuiApp": ".core",
    "VBox": ".layout",
    "Widget": ".core",
    "build_unified": ".widgets",
    "centered": ".layout",
    "detect_capabilities": ".capabilities",
    "detect_reduced_motion": ".capabilities",
    "event_key": ".core",
    "key_id": ".core",
    "load_theme": ".theme_file",
    "normalize_key": ".core",
    "parse_background": ".terminal",
    "parse_unified": ".widgets",
    "resolve_tracks": ".layout",
    "run_app": ".runner",
    "scheme_named": ".core",
    "theme_from_toml": ".theme_file",
    "theme_named": ".core",
    "theme_names": ".core",
    "title_sequence": ".terminal",
    "walk": ".core",
    "word_diff": ".widgets",
}


def __getattr__(name: str) -> object:
    """Import the module a public name lives in, the first time it is asked for.

    This package is a facade over several subpackages, and a caller that wants
    one name should not pay for the rest of them — the TUI alone holds the
    widget library, the Markdown parser, the diff viewer, and the syntax
    scanners. ``__all__`` is still the public surface.
    """
    try:
        module = _EXPORTS[name]
    except KeyError:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from None
    return getattr(importlib.import_module(module, __name__), name)


def __dir__() -> list[str]:
    """Return the names this package publishes."""
    return sorted(__all__)


__all__ = [
    "AnyEvent",
    "ARROW_DOWN",
    "ARROW_UP",
    "BAR_EMPTY",
    "BAR_FULL",
    "DONE",
    "ELLIPSIS",
    "EXPANDED",
    "FAILED",
    "HEADER",
    "MARKER",
    "PENDING",
    "PROMPT",
    "RULE",
    "RUNNING",
    "SEPARATOR",
    "SKIPPED",
    "SPINNER",
    "STATUS",
    "Anchor",
    "AsyncInput",
    "TuiApp",
    "Binding",
    "Border",
    "Canvas",
    "Collapsible",
    "ColorDepth",
    "Column",
    "Command",
    "CommandRegistry",
    "Completer",
    "CompletionItem",
    "CompletionPopup",
    "Constraints",
    "DARK",
    "DifferentialRenderer",
    "Dialog",
    "DialogAction",
    "DiffLine",
    "DiffSegment",
    "DiffView",
    "EdgeInsets",
    "Event",
    "EventKind",
    "EventType",
    "FocusEvent",
    "FocusManager",
    "HBox",
    "Host",
    "InputDecoder",
    "InputEvent",
    "KeyEvent",
    "Keymap",
    "LIGHT",
    "LineSource",
    "ListItem",
    "ListPage",
    "ListView",
    "Markdown",
    "MarkdownSource",
    "MarkdownView",
    "MouseAction",
    "MouseEvent",
    "Overlay",
    "OverlaySlot",
    "Padding",
    "PasteEvent",
    "Point",
    "ProgressBar",
    "RichText",
    "Rect",
    "ResizeEvent",
    "Rule",
    "Scheduler",
    "Screen",
    "ScreenStack",
    "ScrollView",
    "Size",
    "Slot",
    "Span",
    "Spinner",
    "StaticLines",
    "StatusBar",
    "Style",
    "Table",
    "TaskPanel",
    "Terminal",
    "TerminalRunner",
    "TerminalCapabilities",
    "Text",
    "TextArea",
    "TextEvent",
    "TextLine",
    "Theme",
    "ThemeFileError",
    "Toast",
    "Track",
    "VBox",
    "Widget",
    "build_unified",
    "EXAMPLE",
    "detect_capabilities",
    "detect_reduced_motion",
    "centered",
    "event_key",
    "key_id",
    "load_theme",
    "normalize_key",
    "parse_unified",
    "resolve_tracks",
    "run_app",
    "theme_named",
    "title_sequence",
    "scheme_named",
    "parse_background",
    "ToolTheme",
    "theme_names",
    "theme_from_toml",
    "walk",
    "word_diff",
]
